add tests for storage pods.

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -16,7 +16,15 @@ jobs:
       id: microk8s
       run: |
         kubectl get no
-        kubectl get pods -A
-        sleep 20s
         kubectl get pods -A -o wide
+
+
+        # wait for storage pod to be ready
+        kubectl -n kube-system wait --for=condition=ready pod -l k8s-app=hostpath-provisioner --timeout=10s
+        storage_ready=$?
+
+        if [$storage_ready -ne 0 ]; then
+          echo "Error storage not ready."
+          exit $storage_ready
+        fi 
         
