initial work on launch config

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -6,44 +6,56 @@ jobs:
     runs-on: ubuntu-latest
     name: A job to install MicroK8s
     steps:
-    - uses: balchua/microk8s-actions@master
-      with:
-        channel: '1.26/stable'
-        addons: '["rbac", "dns", "hostpath-storage", "registry"]'
+      - name: build-image
+        run: |
+          mkdir -p $HOME/sideload
+          docker pull alpine:edge
+          docker save alpine:edge > $HOME/sideload/alpine-edge.tar
 
-    - name: Check User
-      run: |
-        id
-        sg microk8s -c 'microk8s status'
+      - uses: balchua/microk8s-actions@feat/launch_config
+        with:
+          channel: "1.28/stable"
+          launch-configuration: "$HOME/microk8s-config.yaml"
+          sideload-image-path: "$HOME/sideload/"
 
-    - name: Check push to local registry
-      run: |
-        docker pull busybox:1
-        echo $REGISTRY_IP
-        docker tag busybox:1 localhost:32000/my-repo/busybox:1
-        docker push localhost:32000/my-repo/busybox:1
-        curl http://localhost:32000/v2/_catalog
-                
-    - name: Test MicroK8s
-      id: microk8s
-      run: |
-        set -ex
-        kubectl get no
-        kubectl get pods -A -o wide
-        sleep 120 # Give it sometime before we start checking for pod readiness.
-        # wait for storage pod to be ready
-        kubectl -n kube-system wait --for=condition=ready pod -l k8s-app=hostpath-provisioner --timeout=60s
-        storage_ready=$?
+      - name: Check Side loaded images
+        run: |
+          sudo microk8s ctr images ls | grep alpine:edge
+          sudo microk8s status --wait-ready
 
-        if [ $storage_ready -ne 0 ]; then
-          echo "Error storage not ready."
-          exit $storage_ready
-        fi
-    - name: Test MicroK8s commands
-      id: microk8s-commands
-      run: |
-        set -ex
-        echo "Executing microk8s status using sg command."
-        sg microk8s -c 'microk8s status'
-        echo "Executing microk8s status using sudo command."
-        sudo microk8s status
+      - name: Check User
+        run: |
+          id
+          sg microk8s -c 'microk8s status'
+
+      - name: Check push to local registry
+        run: |
+          docker pull busybox:1
+          echo $REGISTRY_IP
+          docker tag busybox:1 localhost:32000/my-repo/busybox:1
+          docker push localhost:32000/my-repo/busybox:1
+          curl http://localhost:32000/v2/_catalog
+
+      - name: Test MicroK8s
+        id: microk8s
+        run: |
+          set -ex
+          kubectl get no
+          kubectl get pods -A -o wide
+          sleep 120 # Give it sometime before we start checking for pod readiness.
+          # wait for storage pod to be ready
+          kubectl -n kube-system wait --for=condition=ready pod -l k8s-app=hostpath-provisioner --timeout=60s
+          storage_ready=$?
+
+          if [ $storage_ready -ne 0 ]; then
+            echo "Error storage not ready."
+            exit $storage_ready
+          fi
+      - name: Test MicroK8s commands
+        id: microk8s-commands
+        run: |
+          set -ex
+          echo "Executing microk8s status using sg command."
+          sg microk8s -c 'microk8s status'
+          echo "Executing microk8s status using sudo command."
+          sudo microk8s status
